# Generated by Django 5.1.5 on 2025-03-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': 'экземпляр', 'verbose_name_plural': 'Экземпляры книг'},
        ),
    ]
